### PR TITLE
Feat/multiple instances

### LINKED ISSUE #53: Support Multiple On Same Page
We had this issue reported: https://github.com/primefaces/primefaces/issues/5084

And a PR submitted to fix the issue: https://github.com/primefaces/primefaces/pull/5083

However the PrimeFaces project would prefer not to customize this component and was wondering if you could add this feature to your core library?   You can review that PR there may be a better way to do it?

Thanks for your attention and support!

### PR DESCRIPTION
**Pull request by pazepaze**
This adds support for multiple idle monitors on the same element using an optional unique id.
fixes #53

### CODE REVIEW

**Comment by melloware** [comment]
It looks like this was merged but this is not in the `dist` folder for 1.1.1 ?

**Comment by thorst** [comment]
I'm guessing I ran that manually, if it's not up-to-date? You should just be able to minify the following file:
https://github.com/thorst/jquery-idletimer/blob/master/src/idle-timer.js

I'm honestly a couple of months away from rewriting this without the dependency on jQuery, but I have to finish the bulk of another project first. A new version will be required to finish that other project....

**Comment by melloware** [comment]
That is awesome!   Can't wait to check out the new lib!

**Comment by thorst** [comment]
I've waited long enough that the whole module debate worked itself out, so the new version will be up to modern standards...

**Comment by melloware** [comment]
I still hate the module debate.  Trying to make a library work with CJS, MJS, and IIFE is an absolute nightmare.

**Pull request merged**
